import Link from "next/link";
import { ArrowUpRight, Building2, Factory, Leaf, MapPin, ShieldCheck, Sprout, Waves } from "lucide-react";

const capabilities = [
  { icon: Building2, title: "Residential", text: "Screen local risk signals, nearby services, air quality, and land context before a purchase." },
  { icon: Factory, title: "Industrial", text: "Compare soil conditions, access context, construction suitability, and carbon potential." },
  { icon: Sprout, title: "Agriculture", text: "Evaluate soil health, water management, climate evidence, and crop suitability." }
];

export default function WelcomePage() {
  return <main className="bg-[#e6e9f5] text-slate-900">
    <section className="relative flex min-h-[86svh] overflow-hidden px-5 py-6 sm:px-10">
      <iframe title="World map" className="pointer-events-none absolute inset-0 h-full w-full opacity-60 grayscale" src="https://www.openstreetmap.org/export/embed.html?bbox=55%2C-8%2C115%2C42&layer=mapnik" />
      <div className="absolute inset-0 bg-white/30" />
      <div className="relative z-10 mx-auto flex w-full max-w-6xl flex-col">
        <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center overflow-hidden rounded-lg bg-white shadow-[0_8px_24px_rgba(15,23,42,0.14)]"><img src="/brand/terrascope-logo.png" alt="TerraScope logo" className="h-full w-full scale-[1.45] object-cover" /></div><div><p className="text-lg font-bold tracking-normal">TerraScope</p><p className="text-xs font-medium text-slate-600">location intelligence</p></div></div><Link href="/" className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#1C1C1C] px-3 text-sm font-bold text-white shadow-sm transition hover:bg-[#303030]">Open workspace <ArrowUpRight className="h-4 w-4" /></Link></header>
        <div className="my-auto max-w-3xl py-20"><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-600">Spatial decisions, grounded</p><h1 className="mt-5 text-5xl font-bold leading-[1.05] text-[#1C1C1C] sm:text-7xl">Know the land before you commit.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-700">TerraScope turns a location into an evidence-based screening brief for land, climate, risk, soil, services, and carbon potential.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#1C1C1C] px-4 text-sm font-bold text-white shadow-sm transition hover:bg-[#303030]">Inspect a location <MapPin className="h-4 w-4" /></Link><a href="#capabilities" className="inline-flex h-11 items-center rounded-lg border border-slate-300 bg-white/75 px-4 text-sm font-bold text-slate-700 backdrop-blur transition hover:bg-white">Explore capabilities</a></div></div>
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-slate-600"><Waves className="h-4 w-4" />Global coordinates. Local context.</div>
      </div>
    </section>
    <section id="capabilities" className="px-5 py-16 sm:px-10 sm:py-24"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">One location, three views</p><h2 className="mt-3 text-3xl font-bold text-[#1C1C1C] sm:text-4xl">A clearer starting point for every land decision.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{capabilities.map(({ icon: Icon, title, text }) => <article key={title} className="border border-white/90 bg-white/75 p-6 shadow-sm backdrop-blur"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[#1C1C1C] text-white"><Icon className="h-5 w-5" /></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-white/65 px-5 py-16 sm:px-10"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_1.4fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Evidence, not guesswork</p><h2 className="mt-3 text-3xl font-bold text-[#1C1C1C] sm:text-4xl">Turn coordinates into a defensible screening brief.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="border-l-2 border-[#1C1C1C] pl-4"><ShieldCheck className="h-5 w-5 text-[#1C1C1C]" /><p className="mt-3 text-sm font-bold">Risk-aware context</p><p className="mt-1 text-sm leading-6 text-slate-600">Relevant hazard, air, access, and local service signals appear only when they have useful evidence.</p></div><div className="border-l-2 border-[#1C1C1C] pl-4"><Leaf className="h-5 w-5 text-[#1C1C1C]" /><p className="mt-3 text-sm font-bold">Climate and land evidence</p><p className="mt-1 text-sm leading-6 text-slate-600">Historical climate, live outlooks, soil data, and carbon context support the next conversation with experts.</p></div></div></div></section>
    <footer className="px-5 py-10 sm:px-10"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-sm font-bold text-[#1C1C1C]"><div className="grid h-7 w-7 place-items-center overflow-hidden rounded-md bg-white"><img src="/brand/terrascope-logo.png" alt="" className="h-full w-full scale-[1.45] object-cover" /></div>TerraScope</div><Link href="/" className="text-sm font-bold text-slate-600 transition hover:text-[#1C1C1C]">Enter workspace</Link></div></footer>
  </main>;
}
